module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
    'scope-enum': [
      2,
      'always',
      [
        'mobile',
        'backend',
        'landing',
        'infra',
        'auth',
        'routes',
        'stops',
        'subscriptions',
        'payments',
        'geocoding',
        'graphhopper',
        'paywall',
        'ocr',
        'voice',
        'prototipo',
        'docs',
        'decisions',
        'sessions',
        'claude',
        'deps',
        'tooling',
        'ci',
        'vscode',
        'fix',
        'chore',
        'pix',
        'efi',
        'webhook',
        'lgpd',
        'admin',
        'map',
        'release',
      ],
    ],
  },
};
